#!/bin/bash

set -e

test() {
  swipl -c generate_test.pl --stand_alone=true --goal=main -o a.out
  echo 'generating test...'
  time ./a.out >test.txt
  rm a.out

  echo 'running test...'
  time runhaskell Test.hs <test.txt
}

case "$1" in
  Main.hs)  exec runhaskell Main.hs;;
  Test.hs)  exec runhaskell Test.hs;;
  test)     test;;
  *.hs)     exec ghci "$1";;
  *.pl)     exec swipl "$1";;
esac
